#!/usr/bin/env node
// Writes web/solutions/* and web/compare/* from tools/pages.data.mjs.
//
//   node tools/make-pages.mjs           write the pages
//   node tools/make-pages.mjs --check   fail if any page is stale
//
// ## Why these are generated rather than hand-written
//
// There are fourteen of them and they share a head, a house bar, a header, a footer
// and a call to action. Hand-written, they drift: one page keeps an old nav link,
// another misses a meta tag, and the one nobody re-reads still says `.webm`. The
// content lives in `pages.data.mjs` so the writing can be edited without touching a
// template, and `--check` — wired into the same command as the icon and web-asset
// checks — fails the build if a page on disk no longer matches the data.
//
// The shell is copied from the hand-written pages rather than shared at runtime,
// because this is a static site with no build step for the reader: every page has to
// stand alone as a file Vercel can serve.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SOLUTIONS, COMPARISONS } from "./pages.data.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WEB = path.join(ROOT, "web");
const SITE = "https://guidegen.backpocket.website";
const STORE = "https://chromewebstore.google.com/detail/dijeonandicniffeffbcolhfldommhnp";

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/* Strips the markup we allow inside body copy, so a meta description is never a tag
   soup. The data deliberately carries a little <b> and <code>; a description must not. */
const plain = (s) => String(s).replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();

function shell({ url, title, description, body }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}" />
<!-- Generated by tools/make-pages.mjs from tools/pages.data.mjs. Do not edit by hand:
     the next run overwrites it, and \`--check\` fails the build in the meantime. -->
<meta property="og:site_name" content="GuideGen" />
<meta property="og:type" content="website" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="${esc(description)}" />
<meta property="og:url" content="${SITE}${url}" />
<meta property="og:image" content="${SITE}/og.png" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="GuideGen — a recorded workflow turned into numbered steps" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(title)}" />
<meta name="twitter:description" content="${esc(description)}" />
<meta name="twitter:image" content="${SITE}/og.png" />
<link rel="canonical" href="${SITE}${url}" />
<link rel="icon" href="/favicon.ico" sizes="32x32" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<script src="/assets/theme.js"></script>
<link rel="stylesheet" href="/assets/site.css" />
</head>
<body>

<div class="house-bar">
  <div class="row">
    <a class="hb-brand" href="https://www.backpocket.website/">
      <span class="hb-mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 10.5h15v6.2c0 2.4-2 4.3-4.4 4.3H8.9c-2.4 0-4.4-1.9-4.4-4.3z"/><path d="M6.4 12.4h11.2"/><circle cx="12" cy="18.2" r="0.9" fill="currentColor" stroke="none"/><path d="M8 10.5V6.2"/><path d="M6.8 6.2h2.4"/><path d="M12 10.5V4.6"/><path d="M12 4.6l-1.1 1.9h2.2z" fill="currentColor" stroke="none"/><path d="M16 10.5V7.4"/><circle cx="16" cy="5.6" r="1.8"/></svg></span>
      <span class="hb-wm"><b>backpocket</b>.website</span>
    </a>
    <span class="hb-sep" aria-hidden="true">/</span>
    <span class="hb-here">GuideGen</span>
    <span class="spacer"></span>
    <nav class="hb-nav">
      <a href="https://www.backpocket.website/#tools">All tools</a>
      <a href="https://wrapped.backpocket.website">Wrapped</a>
    </nav>
  </div>
</div>

<header class="site">
  <div class="row">
    <a class="brand" href="/">
      <span class="mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h10M4 12h16M4 18h7"/></svg></span>
      <span>GuideGen</span>
    </a>
    <nav>
      <a href="/solutions">Solutions</a>
      <a href="/compare">Compare</a>
      <a href="/privacy">Privacy</a>
    </nav>
  </div>
</header>

${body}

<footer class="site">
  <div class="wrap row">
    <span>© 2026 GuideGen</span>
    <span class="spacer"></span>
    <a href="/solutions">Solutions</a>
    <a href="/compare">Compare</a>
    <a href="/privacy">Privacy</a>
    <a href="/terms">Terms</a>
    <a href="https://www.backpocket.website/#say-hi">Say hi</a>
  </div>
</footer>

</body>
</html>
`;
}

const ctaBlock = (label) => `
  <section class="tint">
    <div class="wrap narrow" style="text-align:center">
      <h2 class="sec">${esc(label)}</h2>
      <p class="lede" style="margin-left:auto;margin-right:auto">Free, unlimited guides, no watermark and no card.
      Everything runs in your browser until you choose to publish.</p>
      <div class="cta-row" style="justify-content:center">
        <a href="${STORE}" class="btn brand-btn lg" rel="noopener">Add to Chrome — it's free</a>
        <a href="/" class="btn lg">See everything it does</a>
      </div>
    </div>
  </section>`;

// ---------------------------------------------------------------- solutions

function solutionPage(s) {
  const body = `
  <section class="hero">
    <div class="wrap narrow">
      <span class="pill">${esc(s.eyebrow)}</span>
      <h1 class="big">${esc(s.title)}</h1>
      <p class="lede">${s.lede}</p>
      <p class="claim">For: ${esc(s.who)}</p>
      <div class="cta-row">
        <a href="${STORE}" class="btn brand-btn lg" rel="noopener">Add to Chrome — it's free</a>
        <a href="/solutions" class="btn lg">Other ways people use it</a>
      </div>
    </div>
  </section>

  <section>
    <div class="wrap narrow">
      <div class="sol-points">
${s.points
  .map(
    ([h, p]) => `        <div class="sol-point"><h3>${esc(h)}</h3><p>${p}</p></div>`
  )
  .join("\n")}
      </div>
    </div>
  </section>
${ctaBlock(s.cta)}`;
  return shell({
    url: `/solutions/${s.slug}`,
    title: `${plain(s.title)} — GuideGen`,
    description: plain(s.lede).slice(0, 300),
    body,
  });
}

function solutionsIndex() {
  const body = `
  <section class="hero">
    <div class="wrap narrow">
      <span class="pill">Solutions</span>
      <h1 class="big">One recording, and a different job every time</h1>
      <p class="lede">The same two minutes of work becomes a bug report, an SOP, an onboarding walkthrough or a
      briefing for a model. These are the ways people actually use it.</p>
    </div>
  </section>

  <section>
    <div class="wrap">
      <div class="sol-grid">
${SOLUTIONS.map(
  (s) => `        <a class="sol-card" href="/solutions/${s.slug}">
          <span class="eyebrow">${esc(s.eyebrow)}</span>
          <h3>${esc(s.nav)}</h3>
          <p>${esc(plain(s.lede).slice(0, 140))}…</p>
        </a>`
).join("\n")}
      </div>
    </div>
  </section>
${ctaBlock("Pick one and try it")}`;
  return shell({
    url: "/solutions",
    title: "Solutions — GuideGen",
    description:
      "Bug reports, SOPs, onboarding walkthroughs, support answers and AI handoffs — the ways people use one GuideGen recording.",
    body,
  });
}

// ---------------------------------------------------------------- comparisons

function comparePage(c) {
  const body = `
  <section class="hero">
    <div class="wrap narrow">
      <span class="pill">Compare</span>
      <h1 class="big">${esc(c.title)}</h1>
      <p class="lede">${c.lede}</p>
      <div class="cta-row">
        <a href="${STORE}" class="btn brand-btn lg" rel="noopener">Try GuideGen — it's free</a>
        <a href="/compare" class="btn lg">All comparisons</a>
      </div>
    </div>
  </section>

  <section>
    <div class="wrap narrow">
      <h2 class="sec">Where ${esc(c.rival)} is the better choice</h2>
      <p class="lede">Written first, and honestly. A comparison page that cannot name a single thing the other product
      does better is marketing, not information.</p>
      <ul class="cmp-list them">
${c.theyWin.map((t) => `        <li>${esc(t)}</li>`).join("\n")}
      </ul>
    </div>
  </section>

  <section class="tint">
    <div class="wrap narrow">
      <h2 class="sec">Where GuideGen wins</h2>
      <div class="sol-points">
${c.weWin.map(([h, p]) => `        <div class="sol-point"><h3>${esc(h)}</h3><p>${p}</p></div>`).join("\n")}
      </div>
    </div>
  </section>

  <section>
    <div class="wrap narrow">
      <h2 class="sec">Which one to pick</h2>
      <p class="lede">${esc(c.verdict)}</p>
    </div>
  </section>
${ctaBlock("Try it on your next workflow")}`;
  return shell({
    url: `/compare/${c.slug}`,
    title: `${plain(c.title)} — an honest comparison`,
    description: plain(c.lede).slice(0, 300),
    body,
  });
}

function compareIndex() {
  const body = `
  <section class="hero">
    <div class="wrap narrow">
      <span class="pill">Compare</span>
      <h1 class="big">GuideGen against the alternatives</h1>
      <p class="lede">Each of these names what the other product does better before it says anything about ours.
      Every claim is either something the competitor publishes themselves or something structural about how their
      product works — there are no invented numbers on these pages.</p>
    </div>
  </section>

  <section>
    <div class="wrap">
      <div class="sol-grid">
${COMPARISONS.map(
  (c) => `        <a class="sol-card" href="/compare/${c.slug}">
          <span class="eyebrow">Comparison</span>
          <h3>${esc(c.title)}</h3>
          <p>${esc(plain(c.lede).slice(0, 140))}…</p>
        </a>`
).join("\n")}
      </div>
    </div>
  </section>
${ctaBlock("Or just try it")}`;
  return shell({
    url: "/compare",
    title: "Compare GuideGen — Guidejar, Scribe, Tango, Guidde, Supademo",
    description:
      "Honest comparisons between GuideGen and the other step-by-step guide tools, including what each of them does better.",
    body,
  });
}

// ---------------------------------------------------------------- write / check

const files = [
  ["solutions/index.html", solutionsIndex()],
  ["compare/index.html", compareIndex()],
  ...SOLUTIONS.map((s) => [`solutions/${s.slug}.html`, solutionPage(s)]),
  ...COMPARISONS.map((c) => [`compare/${c.slug}.html`, comparePage(c)]),
];

const check = process.argv.includes("--check");
let stale = 0;

for (const [rel, html] of files) {
  const dest = path.join(WEB, rel);
  const cur = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : null;
  if (cur === html) continue;
  if (check) {
    console.log(`stale: web/${rel}`);
    stale++;
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, html);
  }
}

if (check) {
  if (stale) {
    console.log(`\n${stale} page(s) out of date. Run: node tools/make-pages.mjs`);
    process.exit(1);
  }
  console.log(`solutions and comparison pages match tools/pages.data.mjs (${files.length} files)`);
} else {
  console.log(`wrote ${files.length} pages into web/solutions and web/compare`);
}
